project_name: pre-commit-makefile

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    main: ./cmd/pre-commit-makefile

brews:
  - repository:
      owner: shini4i
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/shini4i/pre-commit-makefile
    description: "A tool that parses Makefile targets and automatically updates the project's README with a list of available targets and their descriptions"
    license: "MIT"

changelog:
  use:
    github-native
