- id: makefile-readme-updater
  name: makefile-readme-updater
  description: Update README.md based on Makefile
  entry: pre-commit-makefile
  language: system
  types: [file]
  files: '^Makefile$'
  args: []
