- id: makefile-readme-updater
  name: makefile-readme-updater
  description: Update README.md based on Makefile
  entry: pre-commit-makefile run
  language: system
  types: [file]
  files: '^Makefile$'
  args: []
- id: makefile-validator
  name: makefile-validator
  description: Validate Makefile
  entry: pre-commit-makefile validate
  language: system
  types: [file]
  files: '^Makefile$'
  args: []
